# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  # schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  # push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.GITHUB_TOKEN }}

          # Options
          user: musicminion
          template: classic
          base: header
          config_timezone: Asia/Shanghai
          plugin_followup: yes
          plugin_followup_sections: user
          plugin_notable: yes
          plugin_rss: yes
          plugin_rss_source: http://blog.ayaka.space/rss2.xml
          plugin_rss_limit: 4