name: Clean Images

on:
    schedule:
        - cron: '0 0 * * *' # 每天执行一次，UTC时间 00:00
    workflow_dispatch:


jobs:
  clean-images:
    runs-on: ubuntu-latest
    steps:
        - name: Delete 'untaged' containers
          uses: snok/container-retention-policy@v2
          with:
            image-names: blog
            cut-off: 1 min ago UTC
            account-type: personal
            untagged-only: true
            token: ${{ secrets.GITHUB_TOKEN }}
            token-type: github-token